#!/bin/bash

set -e
set -x

if [ "$1" == "" ]; then
  2>&1 "Unspecified model, bailing"
  exit 1
fi

LANGUAGE="en_US.UTF-8"

export DEBIAN_FRONTEND="noninteractive"
export LANG=C

#change hostname
TMP_HOSTNAME="horizon-config-device"

# workaround for services starting at install time (in chroot so this doesn't work)
echo exit 101 > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

echo "$TMP_HOSTNAME" > /etc/hostname
sed "/127.0.1.1/d" -i /etc/hosts

wget http://1dd40.http.tor01.cdn.softlayer.net/fauxcon/fauxcon-armhf-0.1.0 -O /usr/bin/fauxcon && chmod +x /usr/bin/fauxcon

wget http://1dd40.http.tor01.cdn.softlayer.net/ip-out/ip-out-armv7l-0.2.0 -O /usr/local/bin/ip-out && chmod +x /usr/local/bin/ip-out

systemctl disable pollinate.service

systemctl enable systemd-networkd
systemctl enable systemd-resolved
systemctl enable systemd-timesyncd

# don't let these install
apt-mark hold cloud-init open-iscsi grub-legacy-ec2

rm -Rf /seed

# hose workaround for services starting
rm /usr/sbin/policy-rc.d

# fix that bullshit iface renaming
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# remove stuff that takes up space
rm -rf /var/cache/*

yes "horizon" | passwd root
passwd -u root

echo "-----------------------------------------------"
echo "   image chroot setup completed successfully"
echo "-----------------------------------------------"

sync
