#!/bin/bash

set -e
set -x

if [ "$1" == "" ]; then
  2>&1 "Unspecified model, bailing"
  exit 1
fi

LANGUAGE="en_US.UTF-8"

export DEBIAN_FRONTEND="noninteractive"
export LANG=C

# Set locale
echo -e "LANG=C" >> /etc/environment

cat << EOF | debconf-set-selections
locales   locales/locales_to_be_generated multiselect     en_US.UTF-8 UTF-8
EOF

rm /etc/locale.gen
dpkg-reconfigure -f noninteractive locales
update-locale LANG=C

cat << EOF | debconf-set-selections
locales   locales/default_environment_locale select       en_US.UTF-8
EOF

echo 'Reconfigured locale' >> /dev/kmsg

#change hostname
TMP_HOSTNAME="horizon-config-device"

# workaround for services starting at install time (in chroot so this doesn't work)
echo exit 101 > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

# N.B.: the net.ifnames setting ensures names like wlan0, etc.; this is necessary for the systemd-networkd and udev configs in the seed/fs to work
# last console is only one shown init and console in single-user mode. this is HDMI
echo "net.ifnames=0 dwc_otg.lpm_enable=0 kgdboc=ttyAMA0,115200 console=ttyAMA0,115200 console=tty1 consoleblank=0 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait noplymouth" > /boot/cmdline.txt

sed -i 's/#kernel.printk = 3 4 1 3/kernel.printk = 3 4 1 3/' /etc/sysctl.conf

sed -i 's/^PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

sed -i 's|#precedence ::ffff:0:0/96  100|precedence ::ffff:0:0/96  100|' /etc/gai.conf

# temporarily disable automatic updates to prioritize horizon firstboot setup
sed -i 's|"${distro_id}:${distro_codename}-security";|//"${distro_id}:${distro_codename}-security";|' /etc/apt/apt.conf.d/50unattended-upgrades

apt-mark hold linux-headers-raspi2 linux-image-raspi2 linux-raspi2 linux-firmware linux-firmware-raspi2

# need to skip the flash kernel step b/c we build on non-pi devices
export FLASH_KERNEL_SKIP=1

apt update && apt install -o Dpkg::Options::="--force-confold" -y sysstat htop iftop iotop jq screen bridge-utils rsyslog logrotate crda iw wireless-tools wpasupplicant wireless-regdb curl iptables aufs-tools docker.io plymouth plymouth-label plymouth-themes snapd

# do upgrades
apt upgrade -y

# sometimes this includes more than above
unattended-upgrade

echo "$TMP_HOSTNAME" > /etc/hostname
sed "/127.0.1.1/d" -i /etc/hosts

wget http://1dd40.http.tor01.cdn.softlayer.net/fauxcon/fauxcon-armhf-0.1.0 -O /usr/bin/fauxcon && chmod +x /usr/bin/fauxcon

wget http://1dd40.http.tor01.cdn.softlayer.net/ip-out/ip-out-armv7l-0.1.0 -O /usr/local/bin/ip-out && chmod +x /usr/local/bin/ip-out

systemctl disable snapd.refresh.timer
systemctl disable lxd.service
systemctl disable pollinate.service

systemctl enable docker
systemctl enable rc-local.service

systemctl enable systemd-networkd
systemctl enable systemd-resolved
systemctl enable systemd-timesyncd

#fix up sar collection
sed -i 's/ENABLED=.*/ENABLED="true"/' /etc/default/sysstat

# deprecated
rm /etc/default/docker

# TODO: do more safe editing of this to prep for distros using it
cat > /etc/docker/daemon.json <<EOF
{
  "log-driver": "syslog",
  "storage-driver": "aufs"
}
EOF

sed -i 's,X11Forwarding yes,X11Forwarding no,g' /etc/ssh/sshd_config

apt -y purge cloud-init nano resolvconf open-iscsi

rm -Rf /var/lib/cloud /etc/cloud /etc/resolvconf

# don't let this install
apt-mark hold cloud-init

rm -Rf /seed

dpkg --configure -a

# autoremove unneeded packages
apt-get autoremove -y

# remove old kernel b/c that doesn't seem to get removed by later kernel remove cmd

dpkg-reconfigure -plow unattended-upgrades

# hose workaround for services starting
rm /usr/sbin/policy-rc.d

# hose dist files for apt
find /etc/apt/apt.conf.d -type f -iname "*.dist" -exec rm {} \;

# fix that bullshit iface renaming
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# remove stuff that takes up space
rm -rf /var/cache/*

yes "horizon" | passwd root
passwd -u root

echo "-----------------------------------------------"
echo "   image chroot setup completed successfully"
echo "-----------------------------------------------"

sync
