#!/bin/bash

set -e
set -x

MASTER="summit.hovitos.engineering"
LANGUAGE="en_US.UTF-8"

export DEBIAN_FRONTEND="noninteractive"
export LANG=C

# Set locale
echo -e "LANG=C" >> /etc/environment

cat << EOF | debconf-set-selections
locales   locales/locales_to_be_generated multiselect     en_US.UTF-8 UTF-8
EOF

rm /etc/locale.gen
dpkg-reconfigure -f noninteractive locales
update-locale LANG=C

cat << EOF | debconf-set-selections
locales   locales/default_environment_locale select       en_US.UTF-8
EOF

echo 'Reconfigured locale' >> /dev/kmsg

#change hostname
TMP_HOSTNAME="horizon-config-device"

# workaround for services starting at install time (in chroot so this doesn't work)
echo exit 101 > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

# N.B.: the net.ifnames setting ensures names like wlan0, etc.; this is necessary for the systemd-networkd and udev configs in the seed/fs to work
# because of some funky journald setting, this console order causes it to prefer the cable to HDMI
echo "net.ifnames=0 dwc_otg.lpm_enable=0 kgdboc=ttyAMA0,115200 console=tty1 console=ttyAMA0,115200 consoleblank=0 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait" > /boot/cmdline.txt

sed -i 's/#kernel.printk = 3 4 1 3/kernel.printk = 3 4 1 3/' /etc/sysctl.conf

sed -i 's/^PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

sed -i 's|#precedence ::ffff:0:0/96  100|precedence ::ffff:0:0/96  100|' /etc/gai.conf

# temporarily disable automatic updates to prioritize horizon firstboot setup
sed -i 's|"${distro_id}:${distro_codename}-security";|//"${distro_id}:${distro_codename}-security";|' /etc/apt/apt.conf.d/50unattended-upgrades

# hold the kernel package until we deal with the failed symlink on install
apt-mark hold linux-raspi2

apt-get update && apt-get install -o Dpkg::Options::="--force-confold" -y sysstat atop htop iftop iotop jq screen bridge-utils rsyslog logrotate crda iw wireless-tools wpasupplicant wireless-regdb curl iptables aufs-tools docker.io plymouth-themes plymouth-label

# do upgrades
apt-get upgrade -y
#unattended-upgrades -v

# get a version that won't bail on pi2
(cd /tmp;
  curl -o snapd_2.14.2.deb http://launchpadlibrarian.net/282136570/snapd_2.14.2~16.04_armhf.deb &&
    dpkg --install ./snapd_2.14.2.deb)

# don't let this one upgrade
apt-mark hold snapd

echo "$TMP_HOSTNAME" > /etc/hostname
sed "/127.0.1.1/d" -i /etc/hosts

wget http://1dd40.http.tor01.cdn.softlayer.net/fauxcon/fauxcon-armhf-0.1.0 -O /usr/bin/fauxcon && chmod +x /usr/bin/fauxcon

wget http://1dd40.http.tor01.cdn.softlayer.net/colonus_agent/colonus_agent-8118d814 -O /bin/colonus_agent && chmod +x /bin/colonus_agent

systemctl disable snapd.refresh.timer
systemctl disable lxd.service

systemctl enable atop
systemctl enable docker
systemctl enable rc-local.service

systemctl enable systemd-networkd
systemctl enable systemd-resolved
systemctl enable systemd-timesyncd

#fix up sysstat
sed -i 's/ENABLED=.*/ENABLED="true"/' /etc/default/sysstat

sed -i 's/^#DOCKER_OPTS=.*$/DOCKER_OPTS="--log-driver=syslog --storage-driver=aufs"/' /etc/default/docker

sed -i 's,X11Forwarding yes,X11Forwarding no,g' /etc/ssh/sshd_config

apt-get -y purge cloud-init nano resolvconf open-iscsi

rm -Rf /var/lib/cloud /etc/cloud /etc/resolvconf

# don't let this install
apt-mark hold cloud-init

rm -Rf /seed

# autoremove unneeded packages
apt-get autoremove -y

# hose workaround for services starting
rm /usr/sbin/policy-rc.d

apt-mark unhold linux-raspi2

# fix that bullshit iface renaming
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

yes "horizon" | passwd root
passwd -u root

echo "-----------------------------------------------"
echo "   image chroot setup completed successfully"
echo "-----------------------------------------------"

sync
