#!/bin/bash -e

# TODO: figure out why the "quiet" mode affects behavior and not just logging
echo -n "normal" > /sys/module/apparmor/parameters/audit
for i in /sys/devices/system/cpu/cpu[0-9]*/cpufreq/scaling_governor; do echo "ondemand" > $i; done

mkdir -p /var/snap/bluehorizon/common/config

if [ -e /boot/firmware/horizon/config ]; then
  cp -af /boot/firmware/horizon/config /var/snap/bluehorizon/common/
fi

# stuff from /var may overwrite the boot stuff
if [ -e /var/horizon/config ]; then
  cp -af /var/horizon/config /var/snap/bluehorizon/common/
fi
